### ISSUE TITLE
Add a proper readme and contributor docs

### ISSUE THREAD

**Issue by andrew** [24pullrequests/dasher#1]
Similar to the main 24pullrequests repo

**Comment by dougaitken** [comment]
Gonna throw something together for this. 

I'm guessing that Dasher reads the GitHub API for any PR from users who authenticated with the 24PRs "app"? 

edit - it looks like dasher just tracks all pullrequestevent's which have an open status?

**Comment by andrew** [comment]
Yep that's right, thanks!
